version: '3.3'

services:
  api-prod:
    container_name: rest-api-prod
    restart: unless-stopped
    build: 
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - 5000:5000
    environment:
      - MONGODB_URL=mongodb://mongo:27017/restAPI
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    networks:
      - devat

  client-prod:
    container_name: client-prod
    restart: unless-stopped
    build: 
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    depends_on:
      - api-prod
    networks:
      - devat

  mongo:
    image: mongo:5.0.5
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - devat

  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - devat

  nginx:
    image: nginx:1.21.5-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
    depends_on:
      - api-prod
      - client-prod
    networks:
      - devat

  certbot:
    container_name: certbot
    image: certbot/certbot:v1.9.0
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email atvn@devat.xyz --agree-tos --no-eff-email --force-renewal -d devat.xyz  -d www.devat.xyz

volumes:
  mongodb:
  redis:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  devat: